#!/usr/bin/env python
""" Used to test the python threading model.
    
    SUBSCRIBERS:
       sleep (std_msgs/Duration) - duration of sleep, in seconds 

  Essentially, have one or more publishers publish on sleep at various rates.
  The callback will print diagnostic information.

from std_msgs.msg import Int
"""

import rospy
import threading
from std_msgs.msg import Duration


def sleeper(msg):
    rospy.loginfo("Sleeping for %d sec, %d nsec on thread ID %s.", msg.data.secs, msg.data.nsecs, threading.current_thread())
    rospy.sleep(msg.data)
    rospy.loginfo("Woke up on Thread ID %s", threading.current_thread())

if __name__  == "__main__":
    rospy.init_node("sub")
    rospy.Subscriber("sleep", Duration, sleeper)
    rospy.spin()
