#!/usr/bin/env python
""" Creates two timers, printing diagnostic information about their threads """

import rospy
import threading

def callback1(data):
    rospy.loginfo("Callback 1: Thread Id %s", threading.current_thread())

def callback2(data):
    rospy.loginfo("Callback 2: Thread Id %s", threading.current_thread())

def main():
   rospy.init_node("timers")
   rospy.loginfo("Main Thread Id %s", threading.current_thread())
   rospy.Timer(rospy.Duration(1), callback1)
   rospy.Timer(rospy.Duration(5), callback2)
   rospy.spin()

if __name__ == "__main__":
    main()  
